# Generated by Django 3.1.3 on 2020-11-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('url', models.URLField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='TargetSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReleaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.product')),
            ],
            options={
                'verbose_name': 'Product Release History',
                'verbose_name_plural': 'Product Release History',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.targetsite'),
        ),
    ]
