# Generated by Django 3.1.3 on 2020-11-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('panel', '0004_auto_20201120_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchdogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_api_key', models.CharField(max_length=255)),
                ('slack_webhook_uri', models.URLField()),
                ('slack_channel_id', models.CharField(max_length=55)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Watchdog Settings',
                'verbose_name_plural': 'Watchdog Settings',
            },
        ),
    ]
