# Generated by Django 3.1.3 on 2020-11-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_watchdogsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchdogsettings',
            name='slack_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='watchdogsettings',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='watchdogsettings',
            name='slack_webhook_uri',
            field=models.URLField(blank=True),
        ),
    ]
