# Generated by Django 3.1.3 on 2020-11-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20201128_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchdogsettings',
            name='slack_private_channel_ids',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
