# Generated by Django 3.1.3 on 2020-11-30 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_watchdogsettings_slack_private_channel_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchdogsettings',
            name='last_watchdog_run',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='watchdogsettings',
            name='last_watchdog_runtime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchdogsettings',
            name='num_of_watchdog_runs',
            field=models.IntegerField(default=0),
        ),
    ]
