# Generated by Django 3.1.3 on 2020-12-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20201130_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchdogmetadetails',
            options={'verbose_name': 'Watchdog Meta Details', 'verbose_name_plural': 'Watchdog Meta Details'},
        ),
    ]
